"""Add new TranscriptChunk model

Revision ID: 8f13ef8a0a88
Revises: f28b405db8f5
Create Date: 2024-05-10 23:24:52.147170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f13ef8a0a88'
down_revision = 'f28b405db8f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=14), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('start', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_chunk')
    # ### end Alembic commands ###
