"""initial

Revision ID: d56345f3da21
Revises: 
Create Date: 2024-05-12 19:06:09.294291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd56345f3da21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.String(length=14), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcript_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=14), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('start', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('key_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=14), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('starts_from_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['starts_from_id'], ['transcript_chunk.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('key_point')
    op.drop_table('transcript_chunk')
    op.drop_table('video')
    # ### end Alembic commands ###
